#!/bin/sh

PROGRAM=shef
VERSION=0.0.0

SHEF_STDIN_PATH="${SHEF_STDIN_PATH:-/dev/stdin}"
SHEF_RUNTIME_PATH="${SHEF_RUNTIME_PATH:-/run/user/$(id -u)/shef}" || exit 1
SHEF_INCLUDE_PATH="${SHEF_INCLUDE_PATH:-/usr/local/lib/shef}"

SHEF_LOCAL_RUNNER="${SHEF_LOCAL_RUNNER:-sh}"
SHEF_REMOTE_RUNNER="${SHEF_REMOTE_RUNNER:-ssh -T ${SHEF_REMOTE_USER}@${SHEF_REMOTE_HOST} -- sh}"

NL='
'

ERROR_CLOSE_FD='cannot close file descriptor: %s'

tr_arg() {
	tr "$1" "$2" <<- EOF
		$3
	EOF
}

print_usage() {
	indent="$(tr_arg '[:print:]' ' ' "${PROGRAM}")" \
		|| die 'cannot make indentation for synopsis'
	cat <<- EOF || die 'cannot print usage'
		Usage:
		  ${PROGRAM} --version | -V
		  ${PROGRAM} --help
		  ${PROGRAM} [--include-path=<path> | -I <path>]
		  ${indent} [--stdin-runner=<name> | -r <name>]
		  ${indent} [--] [<task>...]
	EOF
}

die() {
	if [ "$1" = --usage ]; then
		show_usage=yes && shift
	fi

	if [ $# -gt 0 ]; then
		format="$1" && shift
		printf "${PROGRAM}: ${format}\n" "$@" 1>&2 || exit 1
	fi

	if [ "${show_usage}" = yes ]; then
		echo 1>&2
		print_usage 1>&2
	fi

	exit 1
}

check_sanity() {
	LC_ALL=C grep --extended-regexp --quiet "$1" <<- EOF || die "$2: '%s'" "$3"
		$3
	EOF
}

find_task() {
	for task; do
		if [ "${task}" = - ]; then
			printf '%s\n' "${SHEF_STDIN_PATH}" || die 'cannot print STDIN path'
		else
			task_files="$(find "${task}" -type f -name '*.sh')" \
				|| die "cannot find task files for the path: '${task}'"
			[ -n "${task_files}" ] || die "there are no task files in the path: '${task_path}'"
			LC_ALL=C sort <<- EOF || die 'cannot sort task files'
				${task_files}
			EOF
		fi
	done
}

# TODO: Doc about hash per runner env
##
# Search library by name and print it real path. If the library has already been found
# in a previous function call, the resulting real path will be empty.
#
# Arguments:
#	$1 Library name
# Globals:
#	$shef_library_path Resulting real path or empty string
# Dies if:
#	- bad library name
#	- cannot find library
##
search_library() {
	check_sanity '^[0-9a-z/-]+$' 'bad library name' "$1"

	hash_key="$(tr_arg '/-' 'S_' "shef_library_hashC$1")" \
		|| die 'cannot make hash key for the library'
	eval "hash_value=\"\${${hash_key}}\"" \
		|| die "cannot take value for the key: '${hash_key}'"

	if [ "${hash_value}" = found ]; then
		shef_library_path=
		return 0
	fi

	IFS=:
	for path in "${shef_include_path}"; do
		shef_library_path="${path}/$1.sh"
		if [ -f "${shef_library_path}" ]; then
			eval "${hash_key}=found" \
				|| die "cannot assign value for the key: '${hash_key}'"
			return 0
		fi
	done

	die "cannot find library: '$1'"
}

include_libraries() {
	while IFS= read -r line; do
		printf '%s\n' "${line}" || die 'cannot print the line to the task'
		case "${line#${line%%[![:blank:]]*}}" in
			\#.*)
				lib="$(
					sed 's/\(^[[:blank:]]*#\.[[:blank:]]*\|[[:blank:]]*$\)//g' <<- EOF
						${line}
					EOF
				)" || die "cannot extract library name from line: '${line}'"

				search_library "${lib}"
				if [ -n "${shef_library_path}" ]; then
					include_libraries < "${shef_library_path}"
				fi
			;;
			\#*|'') continue ;;
			*) break ;;
		esac
	done
	cat
}

# TODO: Doc for file descriptors
run() {
	runner_uppercase_name="$(tr_arg '[:lower:]' '[:upper:]' "$1")" \
		|| die 'cannot convert runner name to uppercase'

	eval "runner=\"\${SHEF_${runner_uppercase_name}_RUNNER}\"" \
		|| die "cannot assign to the runner variable for: '$1'"
	[ -n "${runner}" ] || die "no runner setup for this name: '$1'"

	if [ ! -d "${SHEF_RUNTIME_PATH}" ]; then
		mkdir --parent "${SHEF_RUNTIME_PATH}" \
			|| die "cannot create runtime path: '${SHEF_RUNTIME_PATH}'"
	fi

	fifo="${SHEF_RUNTIME_PATH}/$$.$1.fifo"
	# TODO: Remove clashed old FIFO-file optionaly
	mkfifo "${fifo}" || die "cannot create temporary FIFO: '${fifo}'"
	exec 5<>"${fifo}" 6<"${fifo}" \
		|| die "cannot open file descriptors for FIFO: '${fifo}'"
	rm "${fifo}" || die "cannot remove temporary FIFO: '${fifo}'"

	{
		while IFS= read -r run_file; do
			exec 4<&0 0<&3 || die 'cannot reassign file descriptors: 0, 3'
			include_libraries < "${run_file}"
			exec 0<&4 4<&- || die 'cannot reassign file descriptor 4 and close its'
		done <<- EOF >&5 || die 'cannot output tasks content to the pipe'
			$2
		EOF
	} &

	exec 5>&- || die "${ERROR_CLOSE_FD}" 5

	${runner} <&6 || die "cannot run task file with runner: '${runner}'"
	exec 6<&- || die "${ERROR_CLOSE_FD}" 6

	wait $! || die 'subprocess for task preprocession fails'
}

file_runner() {
	if [ "$1" = "${SHEF_STDIN_PATH}" ]; then
		[ -n "${shef_stdin_runner}" ] \
			|| die 'no runner specified for the task from STDIN'
		shef_runner="${shef_stdin_runner}"
	else
		shef_runner="${1%.sh}"
		shef_runner="${shef_runner##*[/.]}"
	fi
}

cmd_print_version() {
	[ $# -eq 0 ] || die --usage "extra argument: '%s'" "$@"
	printf 'shef version %s\n' "${VERSION}" || die 'cannot print Shef version'
}

cmd_shef() {
	options="$(getopt \
		--options I:r: \
		--longoptions include-path:,stdin-runner: \
		-- "$@")" || die --usage

	eval set -- "${options}"

	shef_include_path="${SHEF_INCLUDE_PATH}"

	while :; do case "$1" in
		--include-path|-I)
			shef_include_path="$2:${shef_include_path}"
			shift 2
		;;
		--stdin-runner|-r)
			check_sanity '^[0-9a-z-]+$' 'bad runner name' "$2"
			shef_stdin_runner="$2"
			shift 2
		;;
		--)
			shift
			break
		;;
	esac done

	task_files="$(find_task "${@:--}")" || die

	exec 3<&0 || die 'cannot open file descriptor 3 for: 0'
	if IFS= read -r task_file; then
		file_runner "${task_file}"
		run_files="${task_file}"

		while IFS= read -r task_file; do
			prev_runner="${shef_runner}"
			file_runner "${task_file}"

			if [ "${prev_runner}" = "${shef_runner}" ]; then
				run_files="${run_files}${NL}${task_file}"
			else
				run "${prev_runner}" "${run_files}"
				run_files="${task_file}"
			fi
		done

		run "${shef_runner}" "${run_files}"
	fi <<- EOF || die 'cannot process task files'
		${task_files}
	EOF
	exec 3<&- || die "${ERROR_CLOSE_FD}" 3
}

case "$1" in
	--version|-V) shift; cmd_print_version "$@" ;;
	--help) print_usage ;;
	*) cmd_shef "$@" ;;
esac
