#!/bin/bash

tasks="$1"
config="$2"
host="$3"

make_script() {
  xargs --no-run-if-empty cat \
    ./server/common/functions.sh \
    "${config}" \
    <(printf '%s\n' "location_environment=$1" "host=${host}")
}

# Local
find ${tasks} -type f -name '*.local.sh' | sort \
  | make_script local \
  | sh || exit 1

# Remote
find ${tasks} -type f -name '*.remote.sh' | sort \
  | make_script remote \
  | ssh -T "root@${host}"
