#!/bin/bash

SHEF_TXT_RUNNER=cat \
	SHEF_STDIN_EXTENSION=txt \
    SHEF_INCLUDE_PATH="${INPUT_DIR}/include-env" \
        "${BINARY}" \
            -I "${INPUT_DIR}/include-opt-1" \
            -I "${INPUT_DIR}/include-opt-2" \
            "${INPUT_DIR}/task-1.txt" - "${INPUT_DIR}/task-3.txt" < "${INPUT_DIR}/stdin"
